# This is a basic workflow to help you get started with Actions

name: Commit Checker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  format-verifier:
    name: Format Verifier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: '.'
          exclude: './bsp'
          extenstions: 'h,hpp,cpp,c'
          clangFormatVersion: 13
          style: file
  
  run-unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test project with googletest.
      uses: arvsrao/googletest-action@master
